### ISSUE TITLE
Iris-Web Pull Access Denied For Repositories

### ISSUE THREAD

**Issue by farukerdem34** [tguard-soc-package/nusantara#5]
# Error

![image](https://github.com/user-attachments/assets/ffa55c5e-c88f-47e3-8940-bd790108bbcc)

# [Nusantara Iris-Web compose.yml](https://github.com/tguard-soc-package/nusantara/blob/main/iris-web/docker-compose.yml)

![image](https://github.com/user-attachments/assets/be1ec635-2609-4b01-8853-e997849903b0)

# [Iris-Web Offical Repository compose.yml](https://github.com/dfir-iris/iris-web/blob/master/docker-compose.yml)

![image](https://github.com/user-attachments/assets/f7761549-1dee-49cc-93cc-4925e3ac487b)

**Comment by bradsap54** [comment]
Hi, farukerdem34!
Regarding the issues you’ve encountered, you can refer to the solutions available on our community website as follows:

http://community.tguard.org/t/error-installation-dfir-iris/41/4?u=tguard-admin

We hope this can resolve the issue.

Thank you!
